/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as ForSchoolsRouteImport } from './routes/for-schools'
import { Route as ForTeachersRouteImport } from './routes/for-teachers'
import { Route as JobsRouteImport } from './routes/jobs'
import { Route as AuthenticatedSchoolRouteImport } from './routes/_authenticated/school'
import { Route as AuthenticatedTeacherRouteImport } from './routes/_authenticated/teacher'
import { Route as AuthenticatedSchoolIndexRouteImport } from './routes/_authenticated/school.index'
import { Route as AuthenticatedSchoolApplicantsRouteImport } from './routes/_authenticated/school.applicants'
import { Route as AuthenticatedSchoolJobsRouteImport } from './routes/_authenticated/school.jobs'
import { Route as AuthenticatedSchoolProfileRouteImport } from './routes/_authenticated/school.profile'
import { Route as AuthenticatedTeacherIndexRouteImport } from './routes/_authenticated/teacher.index'
import { Route as AuthenticatedTeacherApplicationsRouteImport } from './routes/_authenticated/teacher.applications'
import { Route as AuthenticatedTeacherJobsRouteImport } from './routes/_authenticated/teacher.jobs'
import { Route as AuthenticatedTeacherProfileRouteImport } from './routes/_authenticated/teacher.profile'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ForSchoolsRoute = ForSchoolsRouteImport.update({
  id: '/for-schools',
  path: '/for-schools',
  getParentRoute: () => rootRouteImport,
} as any)
const ForTeachersRoute = ForTeachersRouteImport.update({
  id: '/for-teachers',
  path: '/for-teachers',
  getParentRoute: () => rootRouteImport,
} as any)
const JobsRoute = JobsRouteImport.update({
  id: '/jobs',
  path: '/jobs',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSchoolRoute = AuthenticatedSchoolRouteImport.update({
  id: '/school',
  path: '/school',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTeacherRoute = AuthenticatedTeacherRouteImport.update({
  id: '/teacher',
  path: '/teacher',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSchoolIndexRoute =
  AuthenticatedSchoolIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedSchoolRoute,
  } as any)
const AuthenticatedSchoolApplicantsRoute =
  AuthenticatedSchoolApplicantsRouteImport.update({
    id: '/applicants',
    path: '/applicants',
    getParentRoute: () => AuthenticatedSchoolRoute,
  } as any)
const AuthenticatedSchoolJobsRoute = AuthenticatedSchoolJobsRouteImport.update({
  id: '/jobs',
  path: '/jobs',
  getParentRoute: () => AuthenticatedSchoolRoute,
} as any)
const AuthenticatedSchoolProfileRoute =
  AuthenticatedSchoolProfileRouteImport.update({
    id: '/profile',
    path: '/profile',
    getParentRoute: () => AuthenticatedSchoolRoute,
  } as any)
const AuthenticatedTeacherIndexRoute =
  AuthenticatedTeacherIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedTeacherRoute,
  } as any)
const AuthenticatedTeacherApplicationsRoute =
  AuthenticatedTeacherApplicationsRouteImport.update({
    id: '/applications',
    path: '/applications',
    getParentRoute: () => AuthenticatedTeacherRoute,
  } as any)
const AuthenticatedTeacherJobsRoute =
  AuthenticatedTeacherJobsRouteImport.update({
    id: '/jobs',
    path: '/jobs',
    getParentRoute: () => AuthenticatedTeacherRoute,
  } as any)
const AuthenticatedTeacherProfileRoute =
  AuthenticatedTeacherProfileRouteImport.update({
    id: '/profile',
    path: '/profile',
    getParentRoute: () => AuthenticatedTeacherRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/for-schools': typeof ForSchoolsRoute
  '/for-teachers': typeof ForTeachersRoute
  '/jobs': typeof JobsRoute
  '/school': typeof AuthenticatedSchoolRouteWithChildren
  '/teacher': typeof AuthenticatedTeacherRouteWithChildren
  '/school/applicants': typeof AuthenticatedSchoolApplicantsRoute
  '/school/jobs': typeof AuthenticatedSchoolJobsRoute
  '/school/profile': typeof AuthenticatedSchoolProfileRoute
  '/teacher/applications': typeof AuthenticatedTeacherApplicationsRoute
  '/teacher/jobs': typeof AuthenticatedTeacherJobsRoute
  '/teacher/profile': typeof AuthenticatedTeacherProfileRoute
  '/school/': typeof AuthenticatedSchoolIndexRoute
  '/teacher/': typeof AuthenticatedTeacherIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/for-schools': typeof ForSchoolsRoute
  '/for-teachers': typeof ForTeachersRoute
  '/jobs': typeof JobsRoute
  '/school/applicants': typeof AuthenticatedSchoolApplicantsRoute
  '/school/jobs': typeof AuthenticatedSchoolJobsRoute
  '/school/profile': typeof AuthenticatedSchoolProfileRoute
  '/teacher/applications': typeof AuthenticatedTeacherApplicationsRoute
  '/teacher/jobs': typeof AuthenticatedTeacherJobsRoute
  '/teacher/profile': typeof AuthenticatedTeacherProfileRoute
  '/school': typeof AuthenticatedSchoolIndexRoute
  '/teacher': typeof AuthenticatedTeacherIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/for-schools': typeof ForSchoolsRoute
  '/for-teachers': typeof ForTeachersRoute
  '/jobs': typeof JobsRoute
  '/_authenticated/school': typeof AuthenticatedSchoolRouteWithChildren
  '/_authenticated/teacher': typeof AuthenticatedTeacherRouteWithChildren
  '/_authenticated/school/applicants': typeof AuthenticatedSchoolApplicantsRoute
  '/_authenticated/school/jobs': typeof AuthenticatedSchoolJobsRoute
  '/_authenticated/school/profile': typeof AuthenticatedSchoolProfileRoute
  '/_authenticated/teacher/applications': typeof AuthenticatedTeacherApplicationsRoute
  '/_authenticated/teacher/jobs': typeof AuthenticatedTeacherJobsRoute
  '/_authenticated/teacher/profile': typeof AuthenticatedTeacherProfileRoute
  '/_authenticated/school/': typeof AuthenticatedSchoolIndexRoute
  '/_authenticated/teacher/': typeof AuthenticatedTeacherIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/auth'
    | '/contact'
    | '/for-schools'
    | '/for-teachers'
    | '/jobs'
    | '/school'
    | '/teacher'
    | '/school/applicants'
    | '/school/jobs'
    | '/school/profile'
    | '/teacher/applications'
    | '/teacher/jobs'
    | '/teacher/profile'
    | '/school/'
    | '/teacher/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/auth'
    | '/contact'
    | '/for-schools'
    | '/for-teachers'
    | '/jobs'
    | '/school/applicants'
    | '/school/jobs'
    | '/school/profile'
    | '/teacher/applications'
    | '/teacher/jobs'
    | '/teacher/profile'
    | '/school'
    | '/teacher'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/about'
    | '/auth'
    | '/contact'
    | '/for-schools'
    | '/for-teachers'
    | '/jobs'
    | '/_authenticated/school'
    | '/_authenticated/teacher'
    | '/_authenticated/school/applicants'
    | '/_authenticated/school/jobs'
    | '/_authenticated/school/profile'
    | '/_authenticated/teacher/applications'
    | '/_authenticated/teacher/jobs'
    | '/_authenticated/teacher/profile'
    | '/_authenticated/school/'
    | '/_authenticated/teacher/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  AuthRoute: typeof AuthRoute
  ContactRoute: typeof ContactRoute
  ForSchoolsRoute: typeof ForSchoolsRoute
  ForTeachersRoute: typeof ForTeachersRoute
  JobsRoute: typeof JobsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/for-schools': {
      id: '/for-schools'
      path: '/for-schools'
      fullPath: '/for-schools'
      preLoaderRoute: typeof ForSchoolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/for-teachers': {
      id: '/for-teachers'
      path: '/for-teachers'
      fullPath: '/for-teachers'
      preLoaderRoute: typeof ForTeachersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jobs': {
      id: '/jobs'
      path: '/jobs'
      fullPath: '/jobs'
      preLoaderRoute: typeof JobsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/school': {
      id: '/_authenticated/school'
      path: '/school'
      fullPath: '/school'
      preLoaderRoute: typeof AuthenticatedSchoolRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/teacher': {
      id: '/_authenticated/teacher'
      path: '/teacher'
      fullPath: '/teacher'
      preLoaderRoute: typeof AuthenticatedTeacherRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/school/': {
      id: '/_authenticated/school/'
      path: '/'
      fullPath: '/school/'
      preLoaderRoute: typeof AuthenticatedSchoolIndexRouteImport
      parentRoute: typeof AuthenticatedSchoolRoute
    }
    '/_authenticated/school/applicants': {
      id: '/_authenticated/school/applicants'
      path: '/applicants'
      fullPath: '/school/applicants'
      preLoaderRoute: typeof AuthenticatedSchoolApplicantsRouteImport
      parentRoute: typeof AuthenticatedSchoolRoute
    }
    '/_authenticated/school/jobs': {
      id: '/_authenticated/school/jobs'
      path: '/jobs'
      fullPath: '/school/jobs'
      preLoaderRoute: typeof AuthenticatedSchoolJobsRouteImport
      parentRoute: typeof AuthenticatedSchoolRoute
    }
    '/_authenticated/school/profile': {
      id: '/_authenticated/school/profile'
      path: '/profile'
      fullPath: '/school/profile'
      preLoaderRoute: typeof AuthenticatedSchoolProfileRouteImport
      parentRoute: typeof AuthenticatedSchoolRoute
    }
    '/_authenticated/teacher/': {
      id: '/_authenticated/teacher/'
      path: '/'
      fullPath: '/teacher/'
      preLoaderRoute: typeof AuthenticatedTeacherIndexRouteImport
      parentRoute: typeof AuthenticatedTeacherRoute
    }
    '/_authenticated/teacher/applications': {
      id: '/_authenticated/teacher/applications'
      path: '/applications'
      fullPath: '/teacher/applications'
      preLoaderRoute: typeof AuthenticatedTeacherApplicationsRouteImport
      parentRoute: typeof AuthenticatedTeacherRoute
    }
    '/_authenticated/teacher/jobs': {
      id: '/_authenticated/teacher/jobs'
      path: '/jobs'
      fullPath: '/teacher/jobs'
      preLoaderRoute: typeof AuthenticatedTeacherJobsRouteImport
      parentRoute: typeof AuthenticatedTeacherRoute
    }
    '/_authenticated/teacher/profile': {
      id: '/_authenticated/teacher/profile'
      path: '/profile'
      fullPath: '/teacher/profile'
      preLoaderRoute: typeof AuthenticatedTeacherProfileRouteImport
      parentRoute: typeof AuthenticatedTeacherRoute
    }
  }
}

interface AuthenticatedSchoolRouteChildren {
  AuthenticatedSchoolApplicantsRoute: typeof AuthenticatedSchoolApplicantsRoute
  AuthenticatedSchoolJobsRoute: typeof AuthenticatedSchoolJobsRoute
  AuthenticatedSchoolProfileRoute: typeof AuthenticatedSchoolProfileRoute
  AuthenticatedSchoolIndexRoute: typeof AuthenticatedSchoolIndexRoute
}

const AuthenticatedSchoolRouteChildren: AuthenticatedSchoolRouteChildren = {
  AuthenticatedSchoolApplicantsRoute: AuthenticatedSchoolApplicantsRoute,
  AuthenticatedSchoolJobsRoute: AuthenticatedSchoolJobsRoute,
  AuthenticatedSchoolProfileRoute: AuthenticatedSchoolProfileRoute,
  AuthenticatedSchoolIndexRoute: AuthenticatedSchoolIndexRoute,
}

const AuthenticatedSchoolRouteWithChildren =
  AuthenticatedSchoolRoute._addFileChildren(AuthenticatedSchoolRouteChildren)

interface AuthenticatedTeacherRouteChildren {
  AuthenticatedTeacherApplicationsRoute: typeof AuthenticatedTeacherApplicationsRoute
  AuthenticatedTeacherJobsRoute: typeof AuthenticatedTeacherJobsRoute
  AuthenticatedTeacherProfileRoute: typeof AuthenticatedTeacherProfileRoute
  AuthenticatedTeacherIndexRoute: typeof AuthenticatedTeacherIndexRoute
}

const AuthenticatedTeacherRouteChildren: AuthenticatedTeacherRouteChildren = {
  AuthenticatedTeacherApplicationsRoute: AuthenticatedTeacherApplicationsRoute,
  AuthenticatedTeacherJobsRoute: AuthenticatedTeacherJobsRoute,
  AuthenticatedTeacherProfileRoute: AuthenticatedTeacherProfileRoute,
  AuthenticatedTeacherIndexRoute: AuthenticatedTeacherIndexRoute,
}

const AuthenticatedTeacherRouteWithChildren =
  AuthenticatedTeacherRoute._addFileChildren(AuthenticatedTeacherRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedSchoolRoute: typeof AuthenticatedSchoolRouteWithChildren
  AuthenticatedTeacherRoute: typeof AuthenticatedTeacherRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedSchoolRoute: AuthenticatedSchoolRouteWithChildren,
  AuthenticatedTeacherRoute: AuthenticatedTeacherRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  AuthRoute: AuthRoute,
  ContactRoute: ContactRoute,
  ForSchoolsRoute: ForSchoolsRoute,
  ForTeachersRoute: ForTeachersRoute,
  JobsRoute: JobsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
