/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as ForSchoolsRouteImport } from './routes/for-schools'
import { Route as ForTeachersRouteImport } from './routes/for-teachers'
import { Route as JobsRouteImport } from './routes/jobs'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedNotificationsRouteImport } from './routes/_authenticated/notifications'
import { Route as AuthenticatedSchoolRouteImport } from './routes/_authenticated/school'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedTeacherRouteImport } from './routes/_authenticated/teacher'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin.index'
import { Route as AuthenticatedAdminInvoicesRouteImport } from './routes/_authenticated/admin.invoices'
import { Route as AuthenticatedAdminJobsRouteImport } from './routes/_authenticated/admin.jobs'
import { Route as AuthenticatedAdminUsersRouteImport } from './routes/_authenticated/admin.users'
import { Route as AuthenticatedSchoolIndexRouteImport } from './routes/_authenticated/school.index'
import { Route as AuthenticatedSchoolApplicantsRouteImport } from './routes/_authenticated/school.applicants'
import { Route as AuthenticatedSchoolInvoicesRouteImport } from './routes/_authenticated/school.invoices'
import { Route as AuthenticatedSchoolJobsRouteImport } from './routes/_authenticated/school.jobs'
import { Route as AuthenticatedSchoolProfileRouteImport } from './routes/_authenticated/school.profile'
import { Route as AuthenticatedSchoolTeachersRouteImport } from './routes/_authenticated/school.teachers'
import { Route as AuthenticatedTeacherIndexRouteImport } from './routes/_authenticated/teacher.index'
import { Route as AuthenticatedTeacherApplicationsRouteImport } from './routes/_authenticated/teacher.applications'
import { Route as AuthenticatedTeacherJobsRouteImport } from './routes/_authenticated/teacher.jobs'
import { Route as AuthenticatedTeacherOnboardingRouteImport } from './routes/_authenticated/teacher.onboarding'
import { Route as AuthenticatedTeacherProfileRouteImport } from './routes/_authenticated/teacher.profile'
import { Route as LovableEmailTransactionalPreviewRouteImport } from './routes/lovable/email/transactional/preview'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const ForSchoolsRoute = ForSchoolsRouteImport.update({
  id: '/for-schools',
  path: '/for-schools',
  getParentRoute: () => rootRouteImport,
} as any)
const ForTeachersRoute = ForTeachersRouteImport.update({
  id: '/for-teachers',
  path: '/for-teachers',
  getParentRoute: () => rootRouteImport,
} as any)
const JobsRoute = JobsRouteImport.update({
  id: '/jobs',
  path: '/jobs',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedNotificationsRoute =
  AuthenticatedNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSchoolRoute = AuthenticatedSchoolRouteImport.update({
  id: '/school',
  path: '/school',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTeacherRoute = AuthenticatedTeacherRouteImport.update({
  id: '/teacher',
  path: '/teacher',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminInvoicesRoute =
  AuthenticatedAdminInvoicesRouteImport.update({
    id: '/invoices',
    path: '/invoices',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminJobsRoute = AuthenticatedAdminJobsRouteImport.update({
  id: '/jobs',
  path: '/jobs',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminUsersRoute = AuthenticatedAdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedSchoolIndexRoute =
  AuthenticatedSchoolIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedSchoolRoute,
  } as any)
const AuthenticatedSchoolApplicantsRoute =
  AuthenticatedSchoolApplicantsRouteImport.update({
    id: '/applicants',
    path: '/applicants',
    getParentRoute: () => AuthenticatedSchoolRoute,
  } as any)
const AuthenticatedSchoolInvoicesRoute =
  AuthenticatedSchoolInvoicesRouteImport.update({
    id: '/invoices',
    path: '/invoices',
    getParentRoute: () => AuthenticatedSchoolRoute,
  } as any)
const AuthenticatedSchoolJobsRoute = AuthenticatedSchoolJobsRouteImport.update({
  id: '/jobs',
  path: '/jobs',
  getParentRoute: () => AuthenticatedSchoolRoute,
} as any)
const AuthenticatedSchoolProfileRoute =
  AuthenticatedSchoolProfileRouteImport.update({
    id: '/profile',
    path: '/profile',
    getParentRoute: () => AuthenticatedSchoolRoute,
  } as any)
const AuthenticatedSchoolTeachersRoute =
  AuthenticatedSchoolTeachersRouteImport.update({
    id: '/teachers',
    path: '/teachers',
    getParentRoute: () => AuthenticatedSchoolRoute,
  } as any)
const AuthenticatedTeacherIndexRoute =
  AuthenticatedTeacherIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedTeacherRoute,
  } as any)
const AuthenticatedTeacherApplicationsRoute =
  AuthenticatedTeacherApplicationsRouteImport.update({
    id: '/applications',
    path: '/applications',
    getParentRoute: () => AuthenticatedTeacherRoute,
  } as any)
const AuthenticatedTeacherJobsRoute =
  AuthenticatedTeacherJobsRouteImport.update({
    id: '/jobs',
    path: '/jobs',
    getParentRoute: () => AuthenticatedTeacherRoute,
  } as any)
const AuthenticatedTeacherOnboardingRoute =
  AuthenticatedTeacherOnboardingRouteImport.update({
    id: '/onboarding',
    path: '/onboarding',
    getParentRoute: () => AuthenticatedTeacherRoute,
  } as any)
const AuthenticatedTeacherProfileRoute =
  AuthenticatedTeacherProfileRouteImport.update({
    id: '/profile',
    path: '/profile',
    getParentRoute: () => AuthenticatedTeacherRoute,
  } as any)
const LovableEmailTransactionalPreviewRoute =
  LovableEmailTransactionalPreviewRouteImport.update({
    id: '/lovable/email/transactional/preview',
    path: '/lovable/email/transactional/preview',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/for-schools': typeof ForSchoolsRoute
  '/for-teachers': typeof ForTeachersRoute
  '/jobs': typeof JobsRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/terms': typeof TermsRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/notifications': typeof AuthenticatedNotificationsRoute
  '/school': typeof AuthenticatedSchoolRouteWithChildren
  '/settings': typeof AuthenticatedSettingsRoute
  '/teacher': typeof AuthenticatedTeacherRouteWithChildren
  '/admin/invoices': typeof AuthenticatedAdminInvoicesRoute
  '/admin/jobs': typeof AuthenticatedAdminJobsRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/school/applicants': typeof AuthenticatedSchoolApplicantsRoute
  '/school/invoices': typeof AuthenticatedSchoolInvoicesRoute
  '/school/jobs': typeof AuthenticatedSchoolJobsRoute
  '/school/profile': typeof AuthenticatedSchoolProfileRoute
  '/school/teachers': typeof AuthenticatedSchoolTeachersRoute
  '/teacher/applications': typeof AuthenticatedTeacherApplicationsRoute
  '/teacher/jobs': typeof AuthenticatedTeacherJobsRoute
  '/teacher/onboarding': typeof AuthenticatedTeacherOnboardingRoute
  '/teacher/profile': typeof AuthenticatedTeacherProfileRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/school/': typeof AuthenticatedSchoolIndexRoute
  '/teacher/': typeof AuthenticatedTeacherIndexRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/for-schools': typeof ForSchoolsRoute
  '/for-teachers': typeof ForTeachersRoute
  '/jobs': typeof JobsRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/terms': typeof TermsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/notifications': typeof AuthenticatedNotificationsRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/admin/invoices': typeof AuthenticatedAdminInvoicesRoute
  '/admin/jobs': typeof AuthenticatedAdminJobsRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/school/applicants': typeof AuthenticatedSchoolApplicantsRoute
  '/school/invoices': typeof AuthenticatedSchoolInvoicesRoute
  '/school/jobs': typeof AuthenticatedSchoolJobsRoute
  '/school/profile': typeof AuthenticatedSchoolProfileRoute
  '/school/teachers': typeof AuthenticatedSchoolTeachersRoute
  '/teacher/applications': typeof AuthenticatedTeacherApplicationsRoute
  '/teacher/jobs': typeof AuthenticatedTeacherJobsRoute
  '/teacher/onboarding': typeof AuthenticatedTeacherOnboardingRoute
  '/teacher/profile': typeof AuthenticatedTeacherProfileRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/school': typeof AuthenticatedSchoolIndexRoute
  '/teacher': typeof AuthenticatedTeacherIndexRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/for-schools': typeof ForSchoolsRoute
  '/for-teachers': typeof ForTeachersRoute
  '/jobs': typeof JobsRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/terms': typeof TermsRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/notifications': typeof AuthenticatedNotificationsRoute
  '/_authenticated/school': typeof AuthenticatedSchoolRouteWithChildren
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/teacher': typeof AuthenticatedTeacherRouteWithChildren
  '/_authenticated/admin/invoices': typeof AuthenticatedAdminInvoicesRoute
  '/_authenticated/admin/jobs': typeof AuthenticatedAdminJobsRoute
  '/_authenticated/admin/users': typeof AuthenticatedAdminUsersRoute
  '/_authenticated/school/applicants': typeof AuthenticatedSchoolApplicantsRoute
  '/_authenticated/school/invoices': typeof AuthenticatedSchoolInvoicesRoute
  '/_authenticated/school/jobs': typeof AuthenticatedSchoolJobsRoute
  '/_authenticated/school/profile': typeof AuthenticatedSchoolProfileRoute
  '/_authenticated/school/teachers': typeof AuthenticatedSchoolTeachersRoute
  '/_authenticated/teacher/applications': typeof AuthenticatedTeacherApplicationsRoute
  '/_authenticated/teacher/jobs': typeof AuthenticatedTeacherJobsRoute
  '/_authenticated/teacher/onboarding': typeof AuthenticatedTeacherOnboardingRoute
  '/_authenticated/teacher/profile': typeof AuthenticatedTeacherProfileRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/school/': typeof AuthenticatedSchoolIndexRoute
  '/_authenticated/teacher/': typeof AuthenticatedTeacherIndexRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/auth'
    | '/contact'
    | '/faq'
    | '/for-schools'
    | '/for-teachers'
    | '/jobs'
    | '/privacy'
    | '/reset-password'
    | '/terms'
    | '/admin'
    | '/dashboard'
    | '/notifications'
    | '/school'
    | '/settings'
    | '/teacher'
    | '/admin/invoices'
    | '/admin/jobs'
    | '/admin/users'
    | '/school/applicants'
    | '/school/invoices'
    | '/school/jobs'
    | '/school/profile'
    | '/school/teachers'
    | '/teacher/applications'
    | '/teacher/jobs'
    | '/teacher/onboarding'
    | '/teacher/profile'
    | '/admin/'
    | '/school/'
    | '/teacher/'
    | '/lovable/email/transactional/preview'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/auth'
    | '/contact'
    | '/faq'
    | '/for-schools'
    | '/for-teachers'
    | '/jobs'
    | '/privacy'
    | '/reset-password'
    | '/terms'
    | '/dashboard'
    | '/notifications'
    | '/settings'
    | '/admin/invoices'
    | '/admin/jobs'
    | '/admin/users'
    | '/school/applicants'
    | '/school/invoices'
    | '/school/jobs'
    | '/school/profile'
    | '/school/teachers'
    | '/teacher/applications'
    | '/teacher/jobs'
    | '/teacher/onboarding'
    | '/teacher/profile'
    | '/admin'
    | '/school'
    | '/teacher'
    | '/lovable/email/transactional/preview'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/about'
    | '/auth'
    | '/contact'
    | '/faq'
    | '/for-schools'
    | '/for-teachers'
    | '/jobs'
    | '/privacy'
    | '/reset-password'
    | '/terms'
    | '/_authenticated/admin'
    | '/_authenticated/dashboard'
    | '/_authenticated/notifications'
    | '/_authenticated/school'
    | '/_authenticated/settings'
    | '/_authenticated/teacher'
    | '/_authenticated/admin/invoices'
    | '/_authenticated/admin/jobs'
    | '/_authenticated/admin/users'
    | '/_authenticated/school/applicants'
    | '/_authenticated/school/invoices'
    | '/_authenticated/school/jobs'
    | '/_authenticated/school/profile'
    | '/_authenticated/school/teachers'
    | '/_authenticated/teacher/applications'
    | '/_authenticated/teacher/jobs'
    | '/_authenticated/teacher/onboarding'
    | '/_authenticated/teacher/profile'
    | '/_authenticated/admin/'
    | '/_authenticated/school/'
    | '/_authenticated/teacher/'
    | '/lovable/email/transactional/preview'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  AuthRoute: typeof AuthRoute
  ContactRoute: typeof ContactRoute
  FaqRoute: typeof FaqRoute
  ForSchoolsRoute: typeof ForSchoolsRoute
  ForTeachersRoute: typeof ForTeachersRoute
  JobsRoute: typeof JobsRoute
  PrivacyRoute: typeof PrivacyRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  TermsRoute: typeof TermsRoute
  LovableEmailTransactionalPreviewRoute: typeof LovableEmailTransactionalPreviewRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/for-schools': {
      id: '/for-schools'
      path: '/for-schools'
      fullPath: '/for-schools'
      preLoaderRoute: typeof ForSchoolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/for-teachers': {
      id: '/for-teachers'
      path: '/for-teachers'
      fullPath: '/for-teachers'
      preLoaderRoute: typeof ForTeachersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jobs': {
      id: '/jobs'
      path: '/jobs'
      fullPath: '/jobs'
      preLoaderRoute: typeof JobsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/notifications': {
      id: '/_authenticated/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof AuthenticatedNotificationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/school': {
      id: '/_authenticated/school'
      path: '/school'
      fullPath: '/school'
      preLoaderRoute: typeof AuthenticatedSchoolRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/teacher': {
      id: '/_authenticated/teacher'
      path: '/teacher'
      fullPath: '/teacher'
      preLoaderRoute: typeof AuthenticatedTeacherRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/invoices': {
      id: '/_authenticated/admin/invoices'
      path: '/invoices'
      fullPath: '/admin/invoices'
      preLoaderRoute: typeof AuthenticatedAdminInvoicesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/jobs': {
      id: '/_authenticated/admin/jobs'
      path: '/jobs'
      fullPath: '/admin/jobs'
      preLoaderRoute: typeof AuthenticatedAdminJobsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/users': {
      id: '/_authenticated/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AuthenticatedAdminUsersRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/school/': {
      id: '/_authenticated/school/'
      path: '/'
      fullPath: '/school/'
      preLoaderRoute: typeof AuthenticatedSchoolIndexRouteImport
      parentRoute: typeof AuthenticatedSchoolRoute
    }
    '/_authenticated/school/applicants': {
      id: '/_authenticated/school/applicants'
      path: '/applicants'
      fullPath: '/school/applicants'
      preLoaderRoute: typeof AuthenticatedSchoolApplicantsRouteImport
      parentRoute: typeof AuthenticatedSchoolRoute
    }
    '/_authenticated/school/invoices': {
      id: '/_authenticated/school/invoices'
      path: '/invoices'
      fullPath: '/school/invoices'
      preLoaderRoute: typeof AuthenticatedSchoolInvoicesRouteImport
      parentRoute: typeof AuthenticatedSchoolRoute
    }
    '/_authenticated/school/jobs': {
      id: '/_authenticated/school/jobs'
      path: '/jobs'
      fullPath: '/school/jobs'
      preLoaderRoute: typeof AuthenticatedSchoolJobsRouteImport
      parentRoute: typeof AuthenticatedSchoolRoute
    }
    '/_authenticated/school/profile': {
      id: '/_authenticated/school/profile'
      path: '/profile'
      fullPath: '/school/profile'
      preLoaderRoute: typeof AuthenticatedSchoolProfileRouteImport
      parentRoute: typeof AuthenticatedSchoolRoute
    }
    '/_authenticated/school/teachers': {
      id: '/_authenticated/school/teachers'
      path: '/teachers'
      fullPath: '/school/teachers'
      preLoaderRoute: typeof AuthenticatedSchoolTeachersRouteImport
      parentRoute: typeof AuthenticatedSchoolRoute
    }
    '/_authenticated/teacher/': {
      id: '/_authenticated/teacher/'
      path: '/'
      fullPath: '/teacher/'
      preLoaderRoute: typeof AuthenticatedTeacherIndexRouteImport
      parentRoute: typeof AuthenticatedTeacherRoute
    }
    '/_authenticated/teacher/applications': {
      id: '/_authenticated/teacher/applications'
      path: '/applications'
      fullPath: '/teacher/applications'
      preLoaderRoute: typeof AuthenticatedTeacherApplicationsRouteImport
      parentRoute: typeof AuthenticatedTeacherRoute
    }
    '/_authenticated/teacher/jobs': {
      id: '/_authenticated/teacher/jobs'
      path: '/jobs'
      fullPath: '/teacher/jobs'
      preLoaderRoute: typeof AuthenticatedTeacherJobsRouteImport
      parentRoute: typeof AuthenticatedTeacherRoute
    }
    '/_authenticated/teacher/onboarding': {
      id: '/_authenticated/teacher/onboarding'
      path: '/onboarding'
      fullPath: '/teacher/onboarding'
      preLoaderRoute: typeof AuthenticatedTeacherOnboardingRouteImport
      parentRoute: typeof AuthenticatedTeacherRoute
    }
    '/_authenticated/teacher/profile': {
      id: '/_authenticated/teacher/profile'
      path: '/profile'
      fullPath: '/teacher/profile'
      preLoaderRoute: typeof AuthenticatedTeacherProfileRouteImport
      parentRoute: typeof AuthenticatedTeacherRoute
    }
    '/lovable/email/transactional/preview': {
      id: '/lovable/email/transactional/preview'
      path: '/lovable/email/transactional/preview'
      fullPath: '/lovable/email/transactional/preview'
      preLoaderRoute: typeof LovableEmailTransactionalPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminInvoicesRoute: typeof AuthenticatedAdminInvoicesRoute
  AuthenticatedAdminJobsRoute: typeof AuthenticatedAdminJobsRoute
  AuthenticatedAdminUsersRoute: typeof AuthenticatedAdminUsersRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminInvoicesRoute: AuthenticatedAdminInvoicesRoute,
  AuthenticatedAdminJobsRoute: AuthenticatedAdminJobsRoute,
  AuthenticatedAdminUsersRoute: AuthenticatedAdminUsersRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedSchoolRouteChildren {
  AuthenticatedSchoolApplicantsRoute: typeof AuthenticatedSchoolApplicantsRoute
  AuthenticatedSchoolInvoicesRoute: typeof AuthenticatedSchoolInvoicesRoute
  AuthenticatedSchoolJobsRoute: typeof AuthenticatedSchoolJobsRoute
  AuthenticatedSchoolProfileRoute: typeof AuthenticatedSchoolProfileRoute
  AuthenticatedSchoolTeachersRoute: typeof AuthenticatedSchoolTeachersRoute
  AuthenticatedSchoolIndexRoute: typeof AuthenticatedSchoolIndexRoute
}

const AuthenticatedSchoolRouteChildren: AuthenticatedSchoolRouteChildren = {
  AuthenticatedSchoolApplicantsRoute: AuthenticatedSchoolApplicantsRoute,
  AuthenticatedSchoolInvoicesRoute: AuthenticatedSchoolInvoicesRoute,
  AuthenticatedSchoolJobsRoute: AuthenticatedSchoolJobsRoute,
  AuthenticatedSchoolProfileRoute: AuthenticatedSchoolProfileRoute,
  AuthenticatedSchoolTeachersRoute: AuthenticatedSchoolTeachersRoute,
  AuthenticatedSchoolIndexRoute: AuthenticatedSchoolIndexRoute,
}

const AuthenticatedSchoolRouteWithChildren =
  AuthenticatedSchoolRoute._addFileChildren(AuthenticatedSchoolRouteChildren)

interface AuthenticatedTeacherRouteChildren {
  AuthenticatedTeacherApplicationsRoute: typeof AuthenticatedTeacherApplicationsRoute
  AuthenticatedTeacherJobsRoute: typeof AuthenticatedTeacherJobsRoute
  AuthenticatedTeacherOnboardingRoute: typeof AuthenticatedTeacherOnboardingRoute
  AuthenticatedTeacherProfileRoute: typeof AuthenticatedTeacherProfileRoute
  AuthenticatedTeacherIndexRoute: typeof AuthenticatedTeacherIndexRoute
}

const AuthenticatedTeacherRouteChildren: AuthenticatedTeacherRouteChildren = {
  AuthenticatedTeacherApplicationsRoute: AuthenticatedTeacherApplicationsRoute,
  AuthenticatedTeacherJobsRoute: AuthenticatedTeacherJobsRoute,
  AuthenticatedTeacherOnboardingRoute: AuthenticatedTeacherOnboardingRoute,
  AuthenticatedTeacherProfileRoute: AuthenticatedTeacherProfileRoute,
  AuthenticatedTeacherIndexRoute: AuthenticatedTeacherIndexRoute,
}

const AuthenticatedTeacherRouteWithChildren =
  AuthenticatedTeacherRoute._addFileChildren(AuthenticatedTeacherRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedNotificationsRoute: typeof AuthenticatedNotificationsRoute
  AuthenticatedSchoolRoute: typeof AuthenticatedSchoolRouteWithChildren
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedTeacherRoute: typeof AuthenticatedTeacherRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedNotificationsRoute: AuthenticatedNotificationsRoute,
  AuthenticatedSchoolRoute: AuthenticatedSchoolRouteWithChildren,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedTeacherRoute: AuthenticatedTeacherRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  AuthRoute: AuthRoute,
  ContactRoute: ContactRoute,
  FaqRoute: FaqRoute,
  ForSchoolsRoute: ForSchoolsRoute,
  ForTeachersRoute: ForTeachersRoute,
  JobsRoute: JobsRoute,
  PrivacyRoute: PrivacyRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  TermsRoute: TermsRoute,
  LovableEmailTransactionalPreviewRoute: LovableEmailTransactionalPreviewRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
