-- ============================================================================
-- DEMO / SEED DATA — NOT PRODUCTION DATA
-- Fictional schools, jobs and teacher profiles used to make the public jobs
-- page and dashboards look realistic during demos.
-- Everything below is owned by demo accounts on the @jivorna-demo.test domain
-- and every school id starts with 'dddddddd-'. To strip this data later:
--   DELETE FROM public.jobs  WHERE school_id IN (SELECT id FROM public.schools WHERE id::text LIKE 'dddddddd-%');
--   DELETE FROM public.schools WHERE id::text LIKE 'dddddddd-%';
--   -- then delete the @jivorna-demo.test auth accounts.
-- ============================================================================

-- Seeding runs without an authenticated admin, so pause the publish gate and
-- the job-match notification fan-out for the duration of this migration.
ALTER TABLE public.jobs DISABLE TRIGGER enforce_job_publish_is_admin;
ALTER TABLE public.jobs DISABLE TRIGGER jobs_notify_match;

-- ---------------------------------------------------------------- schools ---
INSERT INTO public.schools (id, owner_id, name, board, city, school_type, website, principal_name, hr_name, contact_email, phone, student_count, subscription_status, tagline, description)
VALUES
 ('dddddddd-0000-4000-8000-000000000001','b9f040df-57d1-4a06-b871-3b5203ef8a6d','Silverleaf Public School','CBSE','Pune','Co-ed Day','https://silverleaf.example.com','Dr. Meera Iyer','Rohit Salvi','careers@silverleaf.example.com','+91 20 4000 1101',1850,'active','Curiosity, character, community','A CBSE co-educational day school in Kothrud with a strong STEM and performing-arts programme.'),
 ('dddddddd-0000-4000-8000-000000000002','b9f040df-57d1-4a06-b871-3b5203ef8a6d','Marigold International Academy','IB','Bengaluru','International Day','https://marigold-academy.example.com','Ms. Clara Fernandes','Anitha Reddy','hr@marigold-academy.example.com','+91 80 4000 2202',940,'active','Learning without borders','An IB continuum school on Sarjapur Road offering PYP through Diploma Programme.'),
 ('dddddddd-0000-4000-8000-000000000003','b9f040df-57d1-4a06-b871-3b5203ef8a6d','St. Aubrey High School','ICSE','Mumbai','Co-ed Day','https://staubrey.example.com','Fr. Daniel Pereira','Sneha Kadam','recruitment@staubrey.example.com','+91 22 4000 3303',1420,'trial','Rooted in service since 1971','A long-established ICSE school in Bandra known for its literature and debate culture.'),
 ('dddddddd-0000-4000-8000-000000000004','b9f040df-57d1-4a06-b871-3b5203ef8a6d','Northwind Cambridge School','Cambridge','Gurugram','International Day','https://northwind-cambridge.example.com','Mr. Alistair Grewal','Preeti Chauhan','jobs@northwind-cambridge.example.com','+91 124 400 4404',1120,'active','Think wide, think deep','A Cambridge Assessment International school offering IGCSE and A Levels in Sector 54.'),
 ('dddddddd-0000-4000-8000-000000000005','b9f040df-57d1-4a06-b871-3b5203ef8a6d','Amber Valley Vidyalaya','CBSE','Jaipur','Co-ed Residential','https://ambervalley.example.com','Dr. Suresh Rathore','Kavita Jain','careers@ambervalley.example.com','+91 141 400 5505',760,'trial','A campus that feels like home','A residential CBSE school on the Ajmer Road campus with a focus on sport and Sanskrit.'),
 ('dddddddd-0000-4000-8000-000000000006','b9f040df-57d1-4a06-b871-3b5203ef8a6d','Coral Bay International School','IB','Kochi','International Day','https://coralbay.example.com','Ms. Lakshmi Nair','Jerin Thomas','hiring@coralbay.example.com','+91 484 400 6606',680,'active','Small classes, big horizons','An IB PYP and MYP school near Marine Drive with a marine-ecology field programme.'),
 ('dddddddd-0000-4000-8000-000000000007','b9f040df-57d1-4a06-b871-3b5203ef8a6d','Heritage Grove School','ICSE','Kolkata','Girls Day','https://heritagegrove.example.com','Mrs. Ruma Banerjee','Debjani Ghosh','careers@heritagegrove.example.com','+91 33 4000 7707',1290,'active','Educating women who lead','An ICSE girls'' school in Ballygunge with a celebrated music and mathematics faculty.'),
 ('dddddddd-0000-4000-8000-000000000008','b9f040df-57d1-4a06-b871-3b5203ef8a6d','Ridgeline Cambridge College','Cambridge','Hyderabad','Co-ed Day','https://ridgeline-college.example.com','Dr. Farhan Qureshi','Swathi Rao','people@ridgeline-college.example.com','+91 40 4000 8808',1030,'active','Where enquiry comes first','A Cambridge school in Gachibowli specialising in A Level sciences and computer science.');

-- ------------------------------------------------------------------- jobs ---
INSERT INTO public.jobs (school_id, title, subject, grade, board, location, employment_type, status, min_experience_years, openings, salary_min, salary_max, salary_range, required_skills, benefits, description)
VALUES
 ('dddddddd-0000-4000-8000-000000000001','PGT Physics','Physics','Grades 11-12','CBSE','Pune, Maharashtra','Full-time','published',5,1,780000,1020000,'₹7.8L – ₹10.2L per year',ARRAY['CBSE Physics','Practical labs','JEE foundation'],'Provident fund, annual CPD budget, subsidised lunch','Lead senior-school Physics for Grades 11 and 12, run the practical lab programme and support the JEE foundation track. A post-graduate degree in Physics and B.Ed are required.'),
 ('dddddddd-0000-4000-8000-000000000001','TGT Mathematics','Mathematics','Grades 6-10','CBSE','Pune, Maharashtra','Full-time','published',3,2,540000,720000,'₹5.4L – ₹7.2L per year',ARRAY['Middle-school Mathematics','Differentiated instruction','Google Classroom'],'Provident fund, staff children fee waiver','Teach Mathematics across the middle and secondary years, using differentiated tasks and regular formative assessment to move every learner forward.'),
 ('dddddddd-0000-4000-8000-000000000002','MYP English Language & Literature Teacher','English','MYP Years 1-5','IB','Bengaluru, Karnataka','Full-time','published',4,1,900000,1250000,'₹9L – ₹12.5L per year',ARRAY['IB MYP','Criterion-based assessment','Unit planning'],'Health cover for family, IB workshop sponsorship, relocation support','Plan and teach MYP Language and Literature, write unit planners against MYP criteria and mentor students through the Personal Project.'),
 ('dddddddd-0000-4000-8000-000000000002','PYP Homeroom Teacher','Primary','Grades 1-5','IB','Bengaluru, Karnataka','Full-time','published',2,3,660000,880000,'₹6.6L – ₹8.8L per year',ARRAY['IB PYP','Inquiry-based learning','Early literacy'],'Health cover, IB workshop sponsorship','Own a PYP homeroom, lead transdisciplinary units of inquiry and partner closely with single-subject specialists and parents.'),
 ('dddddddd-0000-4000-8000-000000000002','Diploma Programme Economics Teacher','Economics','Grades 11-12','IB','Bengaluru, Karnataka','Full-time','published',6,1,1100000,1450000,'₹11L – ₹14.5L per year',ARRAY['IB DP Economics','Internal assessment moderation','TOK links'],'Health cover for family, annual flight allowance','Teach DP Economics at Standard and Higher Level, supervise internal assessment commentaries and contribute to the Theory of Knowledge programme.'),
 ('dddddddd-0000-4000-8000-000000000003','Secondary English Teacher','English','Grades 8-10','ICSE','Mumbai, Maharashtra','Full-time','published',3,1,600000,820000,'₹6L – ₹8.2L per year',ARRAY['ICSE English Literature','Creative writing','Debate coaching'],'Provident fund, gratuity, travel allowance','Teach ICSE English Language and Literature to the secondary years and help run our inter-school debate and elocution calendar.'),
 ('dddddddd-0000-4000-8000-000000000003','Visiting Music Teacher (Western Vocals)','Music','Grades 3-8','ICSE','Mumbai, Maharashtra','Part-time','published',2,1,240000,360000,'₹20,000 – ₹30,000 per month',ARRAY['Choral conducting','Piano accompaniment','Ensemble work'],'Flexible three-day week, performance stipend','Direct the junior and senior choirs three days a week and prepare ensembles for the annual concert and Founder''s Day.'),
 ('dddddddd-0000-4000-8000-000000000003','Special Educator','Special Education','Grades 1-10','ICSE','Mumbai, Maharashtra','Full-time','published',4,1,540000,700000,'₹5.4L – ₹7L per year',ARRAY['IEP design','Remedial reading','Parent counselling'],'Provident fund, supervision hours, CPD budget','Design and review individual education plans, deliver remedial support and coach class teachers on inclusive classroom strategies.'),
 ('dddddddd-0000-4000-8000-000000000004','IGCSE Computer Science Teacher','Computer Science','Grades 9-10','Cambridge','Gurugram, Haryana','Full-time','published',3,1,850000,1150000,'₹8.5L – ₹11.5L per year',ARRAY['IGCSE 0478','Python','Pseudocode and algorithms'],'Health cover, device allowance, CAIE training','Deliver IGCSE Computer Science (0478), run the after-school robotics club and prepare students for national coding olympiads.'),
 ('dddddddd-0000-4000-8000-000000000004','A Level Business Studies Teacher','Business Studies','Grades 11-12','Cambridge','Gurugram, Haryana','Full-time','published',5,1,950000,1300000,'₹9.5L – ₹13L per year',ARRAY['CAIE 9609','Case-study teaching','University counselling support'],'Health cover for family, performance bonus','Teach AS and A Level Business Studies, coach the entrepreneurship society and support the university counselling team on commerce applications.'),
 ('dddddddd-0000-4000-8000-000000000004','Primary Years Coordinator','Primary','Grades 1-5','Cambridge','Gurugram, Haryana','Full-time','published',8,1,1200000,1600000,'₹12L – ₹16L per year',ARRAY['Curriculum leadership','Cambridge Primary','Staff appraisal'],'Health cover, leadership coaching, relocation support','Lead the Cambridge Primary team: curriculum mapping, appraisal, parent communication and induction of new teachers.'),
 ('dddddddd-0000-4000-8000-000000000005','PGT Chemistry (Residential)','Chemistry','Grades 11-12','CBSE','Jaipur, Rajasthan','Full-time','published',4,1,700000,920000,'₹7L – ₹9.2L per year',ARRAY['CBSE Chemistry','Lab safety','Boarding pastoral care'],'On-campus housing, all meals, provident fund','Teach senior Chemistry and take a share of residential house duties on our Ajmer Road campus. On-campus accommodation is provided.'),
 ('dddddddd-0000-4000-8000-000000000005','Physical Education Teacher','Physical Education','Grades 4-12','CBSE','Jaipur, Rajasthan','Full-time','published',2,1,420000,580000,'₹4.2L – ₹5.8L per year',ARRAY['Athletics coaching','Sports day planning','First aid certified'],'On-campus housing, sports kit allowance','Run the daily games programme, coach athletics and football squads and plan the inter-house sports calendar.'),
 ('dddddddd-0000-4000-8000-000000000006','MYP Sciences Teacher','Science','MYP Years 1-5','IB','Kochi, Kerala','Full-time','published',3,1,720000,960000,'₹7.2L – ₹9.6L per year',ARRAY['IB MYP Sciences','Field study design','Lab management'],'Health cover, IB workshop sponsorship','Teach integrated MYP Sciences and co-lead our marine-ecology field study week on the backwaters.'),
 ('dddddddd-0000-4000-8000-000000000007','TGT Mathematics','Mathematics','Grades 6-10','ICSE','Kolkata, West Bengal','Contract','published',3,1,480000,640000,'₹4.8L – ₹6.4L per year',ARRAY['ICSE Mathematics','Olympiad coaching','Remedial support'],'Contract completion bonus, travel allowance','A one-year maternity-cover contract teaching ICSE Mathematics to Grades 6 to 10, including weekly olympiad enrichment sessions.');

ALTER TABLE public.jobs ENABLE TRIGGER jobs_notify_match;
ALTER TABLE public.jobs ENABLE TRIGGER enforce_job_publish_is_admin;

-- -------------------------------------------------------- teacher profiles ---
-- Demo teacher accounts already have blank profile rows created at sign-up.
INSERT INTO public.teacher_profiles AS tp (user_id, full_name, email, phone, headline, bio, subjects, grades, boards, languages, experience_years, qualification, current_school, city, state, location, expected_salary, current_salary, notice_period_days, available, available_from, status)
VALUES
 ('a5423d8b-7397-4c98-878f-653491804e1b','Ananya Rao','demo.teacher.1@jivorna-demo.test','+91 98200 11001','PGT Physics with 9 years of CBSE senior-school experience','Physics teacher specialising in Grades 11 and 12, with a strong record in board results and JEE foundation coaching. I run an inquiry-first lab programme and mentor the school science club.',ARRAY['Physics','Mathematics'],ARRAY['Grade 11','Grade 12'],ARRAY['CBSE'],ARRAY['English','Hindi','Marathi'],9,'M.Sc. Physics, B.Ed.','Silver Oak Senior Secondary','Pune','Maharashtra','Pune, Maharashtra',960000,840000,60,true,CURRENT_DATE + 60,'active'),
 ('fab49366-434b-44c4-9e5b-1f1468beff66','Vikram Menon','demo.teacher.2@jivorna-demo.test','+91 98450 11002','IB DP Economics and Business teacher, 12 years across three IB schools','Experienced DP Economics teacher and internal assessment moderator. I have led a commerce department, supported university applications and delivered IB workshops regionally.',ARRAY['Economics','Business Studies'],ARRAY['Grade 11','Grade 12'],ARRAY['IB','Cambridge'],ARRAY['English','Malayalam','Hindi'],12,'MA Economics, IB DP Certificate','Lakeview International','Bengaluru','Karnataka','Bengaluru, Karnataka',1400000,1250000,90,true,CURRENT_DATE + 90,'active'),
 ('78231416-68f1-41f0-8305-811cdd570b01','Fatima Sheikh','demo.teacher.3@jivorna-demo.test','+91 99870 11003','PYP homeroom teacher and early-literacy specialist','Primary teacher with six years in inquiry-based classrooms. I plan transdisciplinary units, run guided reading groups and coach colleagues on formative assessment.',ARRAY['Primary','English'],ARRAY['Grade 1','Grade 2','Grade 3','Grade 4'],ARRAY['IB','ICSE'],ARRAY['English','Hindi','Urdu'],6,'B.El.Ed., IB PYP Category 1','Greenfields Primary','Mumbai','Maharashtra','Mumbai, Maharashtra',780000,660000,30,true,CURRENT_DATE + 30,'active'),
 ('8f1c5f7e-7dc4-4029-b1ee-63b40e52a065','Joseph D''Souza','demo.teacher.4@jivorna-demo.test','+91 96540 11004','Computer Science teacher — IGCSE, A Level and CBSE','I teach programming from Scratch through Python and Java, coach competitive-programming teams and have built two school-wide digital literacy curricula.',ARRAY['Computer Science','Mathematics'],ARRAY['Grade 9','Grade 10','Grade 11','Grade 12'],ARRAY['Cambridge','CBSE'],ARRAY['English','Konkani','Hindi'],7,'B.Tech CSE, B.Ed.','Ashvale Cambridge School','Hyderabad','Telangana','Hyderabad, Telangana',1100000,930000,60,true,CURRENT_DATE + 60,'active'),
 ('e8964b3e-9cbc-4b08-b9c2-28ef080f1363','Neha Kulkarni','demo.teacher.5@jivorna-demo.test','+91 90040 11005','Special educator and remedial reading specialist','Special educator supporting learners with dyslexia, ADHD and processing difficulties. I write and review IEPs, run remedial reading cycles and train mainstream staff on inclusion.',ARRAY['Special Education','English'],ARRAY['Grade 1','Grade 2','Grade 3','Grade 4','Grade 5','Grade 6'],ARRAY['ICSE','CBSE'],ARRAY['English','Marathi','Hindi'],5,'M.Ed. Special Education (RCI registered)','Nirmala Inclusive School','Mumbai','Maharashtra','Mumbai, Maharashtra',700000,560000,45,true,CURRENT_DATE + 45,'active')
ON CONFLICT (user_id) DO UPDATE SET
  full_name = EXCLUDED.full_name, email = EXCLUDED.email, phone = EXCLUDED.phone,
  headline = EXCLUDED.headline, bio = EXCLUDED.bio, subjects = EXCLUDED.subjects,
  grades = EXCLUDED.grades, boards = EXCLUDED.boards, languages = EXCLUDED.languages,
  experience_years = EXCLUDED.experience_years, qualification = EXCLUDED.qualification,
  current_school = EXCLUDED.current_school, city = EXCLUDED.city, state = EXCLUDED.state,
  location = EXCLUDED.location, expected_salary = EXCLUDED.expected_salary,
  current_salary = EXCLUDED.current_salary, notice_period_days = EXCLUDED.notice_period_days,
  available = EXCLUDED.available, available_from = EXCLUDED.available_from,
  status = EXCLUDED.status;
